version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mongodb://db:27017/mydatabase
  db:
    image: mongo
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
